Fix DiskManagerTest
cmu-db/bustub pull request #141
Opened 2021-03-16 06:06 UTC by greenmoon55

- Remove test.db and test.log before test run to avoid test
  failures caused by non-empty test.db and test.log from
  other failed tests.

- Add NOLINTNEXTLINE

2021-03-16 12:37 UTC, apavlo requested changes
Technically this correct, but you should use gtest `SetUp()` and `TearDown()` methods to clean up these files.

2021-03-16 20:20 UTC, greenmoon55 commented
> Technically this correct, but you should use gtest `SetUp()` and `TearDown()` methods to clean up these files.

Sure! I can add `SetUp()` and `TearDown()` methods in recovery_test.cpp too.

2021-04-01 08:28 UTC, greenmoon55 commented
Updated!

2021-04-05 16:35 UTC, apavlo approved these changes
LGTM

2021-04-05 16:35 UTC, merged