chore: run clang-tidy on git diff
cmu-db/bustub pull request #274
Opened 2022-08-22 05:13 UTC by skyzh

Signed-off-by: Alex Chi <iskyzh@gmail.com>

close https://github.com/cmu-db/bustub/issues/272

This PR adds a new Makefile command `check-clang-tidy-diff`, which runs clang-tidy only on files diff to origin/master.

2022-08-23 03:21 UTC, lmwnshn requested changes
LGTM pending minor nits, please also modify the run_clang_tidy.py header to note your changes.

2022-08-23 03:21 UTC, lmwnshn commented on CMakeLists.txt
> +        -only-diff                                                        # Only check diff files to master
```suggestion
        -only-diff                                                        # only check diff files to master
```

Consistent capitalization.

2022-08-23 03:21 UTC, lmwnshn commented on build_support/run_clang_tidy.py
> +    if args.only_diff:
Add a quick short comment before this block to note:

- We added this code
- Why we added this code
- If you ever expect someone to modify this, or if this is porcelain (I don't remember what git commands are porcelain vs plumbing), a quick description of what this code does

1 line each or less is fine, nothing fancy. This is just to make sure that if people replace this with a new run_clang_tidy script in the future, they won't wonder why only_diff is gone.

2022-08-23 06:50 UTC, skyzh commented
Updated and resolved comments. Indeed the file header mentions that there's something called [clang-tidy-diff.py](https://github.com/llvm-mirror/clang-tools-extra/blob/master/clang-tidy/tool/clang-tidy-diff.py). We can also look into possibility with integrating with that script.

2022-08-25 16:48 UTC, lmwnshn approved these changes
LGTM

2022-08-25 16:55 UTC, merged