chore(build): warn on non clang-12 compilers
cmu-db/bustub pull request #282
Opened 2022-08-26 01:46 UTC by skyzh

Signed-off-by: Alex Chi <iskyzh@gmail.com>

close https://github.com/cmu-db/bustub/issues/190

2022-08-26 01:48 UTC, skyzh commented
<img width="764" alt="image" src="https://user-images.githubusercontent.com/4198311/186799046-d5a8802a-6305-4739-8ece-71f248f4fc78.png">

... and it turned out we're not using clang-12 on "Ubuntu 22.04 Clang" CI builds! I'll also fix this...

2022-08-26 01:57 UTC, skyzh commented
Successful configuring cmake will look like:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/4198311/186800074-2d74f6ed-8a22-4613-9414-3d5466385ebd.png">

2022-08-26 20:02 UTC, lmwnshn requested changes
Mostly nits, overall LGTM

2022-08-26 20:02 UTC, lmwnshn commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17) # Compile as C++17
```suggestion
set(CMAKE_CXX_STANDARD 17) # Compile as C++17.
```

2022-08-26 20:02 UTC, lmwnshn commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD_REQUIRED ON) # Require C++17 support
```suggestion
set(CMAKE_CXX_STANDARD_REQUIRED ON) # Require C++17 support.
```

2022-08-26 20:02 UTC, lmwnshn commented on CMakeLists.txt
> +if(NOT DEFINED CLANG_TIDY_BIN)
Are we using a different formatter?

2022-08-26 21:00 UTC, skyzh commented on CMakeLists.txt
> +if(NOT DEFINED CLANG_TIDY_BIN)
Yep, I'll switch back to the CLion one.

2022-08-26 23:49 UTC, skyzh commented
I think I've made a wrong choice to force students to use clang-12 on macOS.

https://github.com/cmu-db/bustub/pull/285

ASAN with leak sanitizer will always report false positives with homebrew-installed LLVM 12. But it works with AppleClang.

```
3: Direct leak of 32 byte(s) in 1 object(s) allocated from:
3:     #0 0x10148cb6c in wrap_calloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3cb6c)
3:     #1 0x1a1ed71e4 in cache_t::insert(objc_selector*, void (*)(), objc_object*)+0x148 (libobjc.A.dylib:arm64+0x201e4)
3:     #2 0xd1090001a1ebede4  (<unknown module>)
```

I guess it's because the dynamically linked artifacts in system (like sanitizer libraries) is built with AppleClang. So maybe it would be a better choice to let students use AppleClang on macOS? (But recommend them to use homebrew's clang-tidy)

2022-08-26 23:54 UTC, skyzh commented
... and AppleClang reports

```
20: ==71198==AddressSanitizer: detect_leaks is not supported on this platform.
```

It's just unsupported.

2022-08-28 17:10 UTC, skyzh commented
ready for review.

2022-08-29 04:23 UTC, lmwnshn approved these changes
Approved for the warning, mostly skimmed everything else. What's our final guidance for ASAN on macOS? Can we stabilize this before p1?

2022-08-29 04:38 UTC, skyzh commented
macOS only has ASAN without LSAN. Linux has ASAN with LSAN built-in. Students can use AppleClang or clang-12, I don't see any issues with them for now with refsol.

The only difference is that, bustub built with clang-12 on macOS will produce strange output when LSAN is forcibly enabled by developers, while AppleClang won't allow developers to enable LSAN. As the default behavior on macOS is to make LSAN disabled with both of the compilers, I'd be happy with any compiler.

Also our CI is currently tested against AppleClang instead of clang-12 on macOS.

2022-08-29 04:39 UTC, skyzh commented
I think this can be stabilized. Students are "recommended" to use clang-12 on macOS, but they're also fine to use AppleClang. LSAN is disabled by default on macOS, no matter which compiler is used.

2022-08-29 13:03 UTC, merged