Bustub to BusTub - Naming consistency
cmu-db/bustub pull request #725
Opened 2024-08-21 16:06 UTC by prashanthduvvada

Changed from Bustub - BusTub (naming consistency)

2024-08-21 20:05 UTC, connortsui20 commented
Could we change these occurrences too?

```
./tools/wasm-bpt-printer/CMakeLists.txt:    target_link_options(wasm-bpt-printer PRIVATE -sEXPORTED_FUNCTIONS=['_BustubInit','_BustubApplyCommand','_free'] -sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','allocateUTF8','UTF8ToString'])
./tools/bpm_bench/bpm_bench.cpp:struct BustubBenchPageHeader {
./tools/bpm_bench/bpm_bench.cpp:  auto *pg = reinterpret_cast<BustubBenchPageHeader *>(data);
./tools/bpm_bench/bpm_bench.cpp:  const auto *pg = reinterpret_cast<const BustubBenchPageHeader *>(data);
./tools/bpm_bench/bpm_bench.cpp:  const auto *pg = reinterpret_cast<const BustubBenchPageHeader *>(data);
./tools/wasm-bpt-printer/wasm-bpt-printer.cpp:auto BustubInit(int leaf_max_size, int internal_max_size) -> int {
./tools/wasm-bpt-printer/wasm-bpt-printer.cpp:auto BustubApplyCommand(const char *input, char *output, uint16_t len) -> int {
./tools/wasm-bpt-printer/extra_files/index.html:        const initialize = Module.cwrap('BustubInit', 'number', ['number', 'number'])
./tools/wasm-bpt-printer/extra_files/index.html:        const executeQuery = Module.cwrap('BustubApplyCommand', 'number', ['string', 'number', 'number'])
./tools/wasm-shell/CMakeLists.txt:    target_link_options(wasm-shell PRIVATE -sEXPORTED_FUNCTIONS=['_BustubInit','_BustubExecuteQuery','_free'] -sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','allocateUTF8','UTF8ToString'])
./src/planner/plan_window_function.cpp:      throw Exception("Bustub currently only support window function with default window frame settings");
./tools/wasm-shell/wasm-shell.cpp:static std::unique_ptr<bustub::BustubInstance> instance = nullptr;
./tools/wasm-shell/wasm-shell.cpp:auto BustubInit() -> int {
./tools/wasm-shell/wasm-shell.cpp:  auto bustub = std::make_unique<bustub::BustubInstance>();
./tools/wasm-shell/wasm-shell.cpp:auto BustubExecuteQuery(const char *input, char *prompt, char *output, uint16_t len) -> int {
./tools/wasm-shell/extra_files/index.html:        const executeQuery = Module.cwrap('BustubExecuteQuery', 'number', ['string', 'number', 'number', 'number'])
./tools/wasm-shell/extra_files/index.html:        const initialize = Module.cwrap('BustubInit', 'number', [])
./test/concurrency/common_checker.h:auto Insert(Transaction *txn, BustubInstance &instance, int v1) -> void {
./test/concurrency/common_checker.h:auto Insert(Transaction *txn, BustubInstance &instance, const std::vector<int> &v1_vec, const std::vector<int> &v2_vec,
./test/concurrency/common_checker.h:auto Delete(Transaction *txn, BustubInstance &instance, int v1) -> void {
./test/concurrency/common_checker.h:auto Delete(Transaction *txn, BustubInstance &instance, const std::vector<int> &d_vec, int d_size = 3) -> void {
./test/concurrency/common_checker.h:auto Scan(Transaction *txn, BustubInstance &instance, const std::vector<int> &v1) -> void {
./test/concurrency/common_checker.h:void Commit(BustubInstance &instance, Transaction *&txn) {
./test/concurrency/common_checker.h:void Abort(BustubInstance &instance, Transaction *&txn) {
./test/concurrency/common_checker.h:auto Begin(BustubInstance &instance, IsolationLevel level) -> Transaction * {
./test/concurrency/common_checker.h:auto GetDbForVisibilityTest(const std::string &name) -> std::shared_ptr<BustubInstance> {
./test/concurrency/common_checker.h:  auto instance = std::make_unique<BustubInstance>();
./test/concurrency/common_checker.h:auto GetDbForCommitAbortTest(const std::string &name) -> std::shared_ptr<BustubInstance> {
./test/concurrency/common_checker.h:  auto instance = std::make_unique<BustubInstance>();
./test/concurrency/common_checker.h:auto GetDbForIsolationTest() -> std::shared_ptr<BustubInstance> {
./test/concurrency/common_checker.h:  auto instance = std::make_unique<BustubInstance>();
./test/concurrency/common_checker.h:auto StartReadTxn(IsolationLevel read_txn_level, BustubInstance &instance, bool read_before_write) -> Transaction * {
./test/concurrency/common_checker.h:auto StartWriteTxn(IsolationLevel write_txn_level, BustubInstance &instance, bool is_delete) -> Transaction * {
./test/concurrency/common_checker.h:auto TryRead(Transaction *txn_r, BustubInstance &instance, ExpectedOutcome o, bool is_delete,
./test/recovery/recovery_test.cpp.disabled:  auto *bustub_instance = new BustubInstance("test.bustub");
./test/recovery/recovery_test.cpp.disabled:  bustub_instance = new BustubInstance("test.bustub");
./test/recovery/recovery_test.cpp.disabled:  auto *bustub_instance = new BustubInstance("test.bustub");
./test/recovery/recovery_test.cpp.disabled:  bustub_instance = new BustubInstance("test.bustub");
./test/recovery/recovery_test.cpp.disabled:  auto *bustub_instance = new BustubInstance("test.bustub");
```

2024-08-21 20:05 UTC, connortsui20 requested changes
See above

2024-08-21 22:40 UTC, prashanthduvvada commented
Changes done.

2024-08-22 00:32 UTC, connortsui20 approved these changes

2024-08-22 00:40 UTC, merged